package option

type Options struct {
	Merge            bool
	Name             string
	Package          string
	JsonTag          bool
	Omitempty        bool
	NestedMode       string // inline or separate
	ConflictStrategy string // strict or loose
	NumberType       string // auto, int, float
	Limits           Limits
}

const (
	NestedInline   = "inline"
	NestedSeparate = "separate"
	ConflictStrict = "strict"
	ConflictLoose  = "loose"
	NumberAuto     = "auto"
	NumberInt      = "int"
	NumberFloat    = "float"
)

func (o *Options) Defaults() {
	if o.Name == "" {
		o.Name = "AutoGenerated"
	}
	if o.Package == "" {
		o.Package = "models"
	}
	if !o.JsonTag {
		o.JsonTag = true
	}
	if o.NestedMode == "" {
		o.NestedMode = "inline"
	}
	if o.ConflictStrategy == "" {
		o.ConflictStrategy = "loose"
	}
	if o.NumberType == "" {
		o.NumberType = "auto"
	}
}
